name: Deploy Backend (staging)

on:
  push:
    branches: [ staging ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy-staging.yml"
      - ".github/workflows/_deploy-backend.yml"

jobs:
  call:
    uses: ./.github/workflows/_deploy-backend.yml
    secrets: inherit
    with:
      environment: staging
      deploy_path: /srv/staging/backend
      service_name: backend-staging.service
      enable_timers: false
