name: Deploy Scheduler to Cloud Run Job

on:
  pull_request:
    branches: ['production']
    paths: 
        - '.github/workflows/ci-scheduler.yml'
        - 'scheduler/**'

jobs:
  setup-build-publish-deploy-scheduler:
    name: Setup, Build, Publish, Deploy Scheduler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.0.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker ${{ vars.GCP_REPO_REGION }}-docker.pkg.dev --quiet

      - name: Build Scheduler Docker Image
        working-directory: ./scheduler
        run: docker build --no-cache --tag ${{ vars.GCP_REPO_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/valsewa/scheduler:${{ github.sha }} .

      - name: Push Scheduler Image to Artifact Registry
        run: docker push ${{ vars.GCP_REPO_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/valsewa/scheduler:${{ github.sha }}

      - name: Deploy Scheduler Cloud Run Job
        run: |
          gcloud run jobs deploy scheduler-job \
            --image=${{ vars.GCP_REPO_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/valsewa/scheduler:${{ github.sha }} \
            --region=${{ vars.GCP_CLOUD_RUN_REGION }} \
            --set-env-vars=BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }} \
            --set-env-vars=SCHEDULER_API_KEY=${{ secrets.SCHEDULER_API_KEY }}
